<?php

/**
 * Copyright 2010 SURFnet B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace OpenConext\EngineBlockBundle\Doctrine\Type;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\ConversionException;
use Doctrine\DBAL\Types\Type;
use OpenConext\EngineBlock\Exception\InvalidArgumentException;
use OpenConext\EngineBlock\Metadata\Coins;

class MetadataCoinType extends Type
{
    const NAME = 'engineblock_metadata_coins';

    public function getSQLDeclaration(array $column, AbstractPlatform $platform): string
    {
        // We want a `TEXT` field declaration in our column, the `LONGTEXT` default causes issues when running the
        // DBMS in strict mode.
        $column['length'] = 65535;
        return $platform->getJsonTypeDeclarationSQL($column);
    }

public function convertToDatabaseValue($value, AbstractPlatform $platform): mixed
{
    if (is_null($value)) {
        return null;
    }

    if ($value instanceof Coins) {
        return $value->toJson();
    }

    throw new ConversionException(
        sprintf(
            'Value "%s" must be null or an instance of Coins to be able to ' .
            'convert it to a database value',
            is_object($value) ? get_class($value) : (string)$value
        )
    );
}

    public function getMappedDatabaseTypes(AbstractPlatform $platform): array
    {
        return parent::getMappedDatabaseTypes($platform); // TODO: Change the autogenerated stub
    }

public function convertToPHPValue($value, AbstractPlatform $platform): mixed
{
    if (is_null($value)) {
        return $value;
    }

    try {
        return Coins::fromJson($value);
    } catch (InvalidArgumentException $e) {
            throw new ConversionException(
                sprintf(
                    'Could not convert database value "%s" to Doctrine Type %s. Expected format: %s',
                    $value,
                    $this->getName(),
                    'valid serialized coin json'
                ),
                0,
                $e
            );
    }
}

    public function getName(): string
    {
        return self::NAME;
    }

    /**
     * @see https://github.com/doctrine/DoctrineBundle/issues/977#issuecomment-497215968
     */
    public function requiresSQLCommentHint(AbstractPlatform $platform) : bool
    {
        return true;
    }
}
